//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronunciation.Core.Database
{
    using System;
    using System.Collections.Generic;

    public partial class DictionaryCategory
    {
        public DictionaryCategory()
        {
            this.DictionaryCategoryMembers = new HashSet<DictionaryCategoryMember>();
        }

        public System.Guid CategoryId { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSystemCategory { get; set; }

        public virtual ICollection<DictionaryCategoryMember> DictionaryCategoryMembers { get; set; }
    }
}
