//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronunciation.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseType
    {
        public ExerciseType()
        {
            this.Exercises = new HashSet<Exercise>();
        }
    
        public int ExerciseTypeId { get; set; }
        public string ExerciseTypeName { get; set; }
        public Nullable<int> Ordinal { get; set; }
    
        public virtual ICollection<Exercise> Exercises { get; set; }
    }
}
