//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronunciation.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int ExerciseId { get; set; }
        public Nullable<int> ExerciseTypeId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string Title { get; set; }
        public string TargetSound { get; set; }
        public string ExecutionNotes { get; set; }
        public Nullable<int> SourcePage { get; set; }
        public Nullable<int> SourceCD { get; set; }
        public Nullable<int> SourceTrack { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ExerciseType ExerciseType { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
