//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronunciation.Core.Database
{
    using System;
    using System.Collections.Generic;

    public partial class RecordedAudio
    {
        public Guid AudioId { get; set; }
        public byte[] RawData { get; set; }
        public DateTime Recorded { get; set; }
        public string TargetKey { get; set; }
        public int TargetTypeId { get; set; }
        public Nullable<Int32> Duration { get; set; }
    }
}
